name: food_app
description: A new Flutter project

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add other packages here
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  bloc: ^9.0.0
  supabase_flutter: ^2.10.0
  flutter_bloc: ^9.1.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Example for assets
  # assets:
  #   - assets/images/
